version: '3.7'
services:
 web_dev:
  build: .
  container_name: flask_app
  ports:
   - "5000:5000"
  volumes:
   - .:/app
  environment:
   - FLASK_ENV=development
   - BASE_URL=http://127.0.0.1:5000/NS/api/
   - DEFAULTHGRAPH=http://localhost:8890/test
   - LOCAL_SPARQL=http://172.19.1.3:8890/sparql
   - URL_SEND_LOCAL_VIRTUOSO=http://172.19.1.3:8890/DAV/test_folder/data
   - CELERY_BROKER_URL='redis://172.19.1.4:6379/0'
   - CELERY_RESULT_BACKEND='redis://172.19.1.4:6379/0'
  networks: 
    test:
      ipv4_address: 172.19.1.1
 
 postgres_compose:
  image: postgres:10
  container_name: "postgres"
  # Setup the username, password, and database name. 
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=ref_ns_sec
  # Maps port 54320 (localhost) to port 5432 on the container. 
  ports:
    - "54320:5432" 
  volumes:
    - ./postgres_data:/var/lib/postgresql/data
  networks: 
    test:
      ipv4_address: 172.19.1.2

 virtuoso:
  image: openlink/virtuoso-opensource-7:7.2
  container_name: virtuoso
  environment:
      #- SPARQL_UPDATE=true
      - VIRTUOSO_DB_USER=demo
      - VIRTUOSO_DB_PASSWORD=chewiens
      - DEFAULT_GRAPH=http://localhost:8890/test
      - DBA_PASSWORD=ummi
      - DAV_PASSWORD=ummi
      #- LOG_FILE_LOCATION=/var/lib/virtuoso-opensource-6.1/db/
      # - VIRTUOSO_INI_FILE=/home/pcerqueira/Lab_Software/refactored_ns/test_compose/virtuoso.ini
  volumes:
    # This volume contains the virtuoso database (virtuoso.db)
    - ./virtuoso_data/db:/opt/virtuoso-opensource/database
    
    # This volume contains a file with a SQL query.
    # This query will give permission to perform updates through SPARQL.
    - ./virtuoso_data/sql_query.sql:/opt/virtuoso-opensource/initdb.d/sql_query.sql
  ports:
    - "8080:8890"
    - "1112:1111"
  networks: 
    test:
      ipv4_address: 172.19.1.3
 
 redis:
  image: redis:5.0.6
  container_name: redis
  networks: 
    test:
      ipv4_address: 172.19.1.4

 
 nginx:
  image: nginx:1.17
  container_name: nginx
  volumes:
   - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
   - /etc/nginx/conf.d:/etc/nginx/conf.d
  ports:
   - "8888:80"
   - "443:443"
  networks: 
    test:
      ipv4_address: 172.19.1.5


networks:
 test:
  ipam: 
    driver: default
    config: 
      - subnet: 172.19.0.0/16
