version: '3.7'
services:
 flask_app:
  build: .
  container_name: flask_app
  ports:
   - "5000:5000"
  #expose:
  # - "8000"
  volumes:
   # this will nullify operations in this directory like
   # downloading files, extracting and installing in this directory
   - .:/app
   - ./pre-computed-data:/app/pre-computed-data
   - ./schema_insertion_temp:/app/schema_insertion_temp
   - ./compressed_schemas:/app/compressed_schemas
   - ./prodigal_training_files:/app/prodigal_training_files
   - ./log_files:/app/log_files
  environment:
   - FLASK_ENV=development
   - BASE_URL=http://127.0.0.1:5000/NS/api/
   - DEFAULTHGRAPH=http://localhost:8890/chewiens
   - LOCAL_SPARQL=http://172.19.1.3:8890/sparql
   - URL_SEND_LOCAL_VIRTUOSO=http://172.19.1.3:8890/DAV/test_folder/data
  #  - CELERY_BROKER_URL=redis://172.19.1.4:6379/0
  #  - CELERY_RESULT_BACKEND=redis://172.19.1.4:6379/0
  networks:
    test:
      ipv4_address: 172.19.1.1
  depends_on:
    - redis
    - postgres_compose
    - virtuoso
  #restart: always
 
 postgres_compose:
  image: postgres:10
  container_name: "postgres"
  # Setup the username, password, and database name.
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=ref_ns_sec
  # Maps port 54320 (localhost) to port 5432 on the container.
  ports:
    - "54320:5432" 
  volumes:
    - ./postgres_data:/var/lib/postgresql/data
  networks: 
    test:
      ipv4_address: 172.19.1.2

 virtuoso:
  image: openlink/virtuoso-opensource-7:7.2
  container_name: virtuoso
  environment:
      #- SPARQL_UPDATE=true
      - VIRTUOSO_DB_USER=demo
      - VIRTUOSO_DB_PASSWORD=chewiens
      - DEFAULT_GRAPH=http://localhost:8890/chewiens
      - DBA_PASSWORD=ummi
      - DAV_PASSWORD=ummi
      #- LOG_FILE_LOCATION=/var/lib/virtuoso-opensource-6.1/db/
      #- VIRTUOSO_INI_FILE=./virtuoso.ini
  volumes:
    # This volume contains the virtuoso database (virtuoso.db)
    - ./virtuoso_data/db:/opt/virtuoso-opensource/database
    
    # This volume contains a file with a SQL query.
    # This query will give permission to perform updates through SPARQL.
    - ./virtuoso_data/sql_query.sql:/opt/virtuoso-opensource/initdb.d/sql_query.sql
  ports:
    - "8890:8890"
    - "1111:1111"
  networks: 
    test:
      ipv4_address: 172.19.1.3
 
 redis:
  image: redis:5.0.6
  container_name: redis
  volumes:
    - ./redis_data:/data
  ports: 
    - "6379:6379"
  networks: 
    test:
      ipv4_address: 172.19.1.4

 loci_worker:
  build: .
  container_name: loci_worker
  command: sh -c "celery -A app.api.routes worker -l info -Q loci_queue -c 1"
  volumes: 
    - .:/app
  depends_on: 
    - redis
  networks: 
    - test

 alleles_worker:
  build: .
  container_name: alleles_worker
  command: sh -c "celery -A app.api.routes worker -l info -Q alleles_queue -c 1"
  volumes: 
    - .:/app
  depends_on: 
    - redis
  networks: 
    - test

 sync_worker:
  build: .
  container_name: sync_worker
  command: sh -c "celery -A app.api.routes worker -l info -Q sync_queue -c 1"
  volumes: 
    - .:/app
  depends_on: 
    - redis
  networks: 
    - test

### Original 
# nginx:
#  build:
#    context: ./nginx
#    dockerfile: Dockerfile.dev
#  container_name: nginx
#  volumes:
#   - /home/ubuntu/chewie_ns/self_certs:/etc/nginx/certs
#  # - ./nginx/error.log:/var/log/nginx/error.log
#  ports:
#   - "80:80"
#   - "443:443"
  #expose:
  # - "8888"
#  depends_on:
#   - flask_app
#   - react_app
#  restart: always
#  networks:
#    test:
#      ipv4_address: 172.19.1.5

## Production
 nginx_react:
  build:
    context: ./frontend_react/chewie_ns
    dockerfile: Dockerfile.prod
  container_name: nginx
  volumes:
   - ./self_certs:/etc/nginx/certs
   - ./compressed_schemas:/var/www/my-app/internal_redirect/compressed_schemas
   - ./prodigal_training_files:/var/www/my-app/internal_redirect/prodigal_training_files
  ports:
   - "443:443"
  depends_on:
   - flask_app
  restart: always
  networks:
    test:
      ipv4_address: 172.19.1.5


# react_app:
#  build:
#    context: ./frontend_react/chewie_ns
#    dockerfile: Dockerfile.dev
#  container_name: react_app
##  volumes:
##   - ./frontend_react/chewie_ns/src:/usr/src/react_app/src
##   - ./frontend_react/chewie_ns/public:/usr/src/react_app/public
#  ports:
#   - "3000:3000"
#  #expose:
#  # - "3000"
#  depends_on:
#   - flask_app
#  environment:
#   - NODE_ENV=development
#  networks:
#    test:
#      ipv4_address: 172.19.1.6


networks:
 test:
  ipam: 
    driver: default
    config: 
      - subnet: 172.19.0.0/16

