# Stage 1 - Building image
FROM node:13 as node

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm install react-scripts@2.0.3 -g

COPY . .

RUN npm run build

# Stage 2 - Running image
FROM nginx:1.17

COPY --from=node /usr/src/app/build /var/www/my-app

RUN rm /etc/nginx/conf.d/*

COPY ./mime.types /etc/nginx/

COPY ./cors.conf /etc/nginx/

COPY ./nginx.conf /etc/nginx/

# COPY ./.htpasswd /etc/nginx/

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
