"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 08905dd07547
Revises: 5b05f6469c15
Create Date: 2020-09-14 13:11:47.702660-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08905dd07547"
down_revision = "5b05f6469c15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
