"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 0a35fa1dd78e
Revises: 8b913eacc183
Create Date: 2021-03-08 07:20:24.475001-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a35fa1dd78e"
down_revision = "8b913eacc183"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
