"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 0a6e5737ba5b
Revises: 77d423f736b1
Create Date: 2021-02-03 04:12:49.759044-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a6e5737ba5b"
down_revision = "77d423f736b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
