"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 1ba2a91570f8
Revises: d831f4f7b1ea
Create Date: 2021-03-02 07:30:23.135684-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ba2a91570f8"
down_revision = "d831f4f7b1ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
