"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 20ba5985f850
Revises: ebcf5d02776b
Create Date: 2020-09-21 05:37:44.045608-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20ba5985f850"
down_revision = "ebcf5d02776b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
