"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 2353a01fd1ea
Revises: 3182b4a52a90
Create Date: 2021-02-19 08:45:05.474580-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2353a01fd1ea"
down_revision = "3182b4a52a90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
