"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 24cc395286fb
Revises: c544daef6c1e
Create Date: 2021-02-03 06:54:24.333061-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24cc395286fb"
down_revision = "c544daef6c1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
