"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 273e02aca531
Revises: 9a859cae87f2
Create Date: 2020-09-21 02:57:33.240218-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "273e02aca531"
down_revision = "9a859cae87f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
