"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 2ddf4d8c19d6
Revises: 87ab413a9ea0
Create Date: 2020-09-19 09:02:29.410309-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ddf4d8c19d6"
down_revision = "87ab413a9ea0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
