"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 3182b4a52a90
Revises: 757c20647557
Create Date: 2021-02-19 05:10:51.991274-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3182b4a52a90"
down_revision = "757c20647557"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
