"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 366df47dad2c
Revises: 57dc094bb3d1
Create Date: 2021-02-03 04:25:04.169710-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "366df47dad2c"
down_revision = "57dc094bb3d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
