"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 472533d0a16a
Revises: e2e97362c426
Create Date: 2021-03-12 03:38:19.651038-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "472533d0a16a"
down_revision = "e2e97362c426"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
