"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 4e1ca92eb9a5
Revises: 64638ca1c84d
Create Date: 2021-02-04 04:43:39.406325-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e1ca92eb9a5"
down_revision = "64638ca1c84d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
