"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 57dc094bb3d1
Revises: 0a6e5737ba5b
Create Date: 2021-02-03 04:20:51.729678-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57dc094bb3d1"
down_revision = "0a6e5737ba5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
