"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 5b05f6469c15
Revises: 8535ceb8ed4e
Create Date: 2020-09-14 03:25:43.512361-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b05f6469c15"
down_revision = "8535ceb8ed4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
