"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 64638ca1c84d
Revises: ef90ab83a49c
Create Date: 2021-02-04 04:27:20.832357-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64638ca1c84d"
down_revision = "ef90ab83a49c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
