"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 6a21b8ea31fd
Revises: ced43aed2403
Create Date: 2021-03-10 06:22:42.372396-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a21b8ea31fd"
down_revision = "ced43aed2403"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
