"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 757c20647557
Revises: 923cc8d5eb7e
Create Date: 2021-02-18 09:34:07.906490-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "757c20647557"
down_revision = "923cc8d5eb7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
