"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 77d423f736b1
Revises: 20ba5985f850
Create Date: 2020-09-22 12:09:14.017344-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77d423f736b1"
down_revision = "20ba5985f850"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
