"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 78fbb708ad0c
Revises: c038aa65ba53
Create Date: 2021-02-03 08:08:52.985270-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78fbb708ad0c"
down_revision = "c038aa65ba53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
