"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 7ef50f339374
Revises: ccbce38126ab
Create Date: 2021-03-12 05:34:28.213086-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef50f339374'
down_revision = 'ccbce38126ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
