"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 8535ceb8ed4e
Revises: dc0acc201ad8
Create Date: 2020-09-14 03:09:16.462123-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8535ceb8ed4e"
down_revision = "dc0acc201ad8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
