"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 87ab413a9ea0
Revises: eaff12dbec3b
Create Date: 2020-09-18 14:41:48.886917-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87ab413a9ea0"
down_revision = "eaff12dbec3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
