"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 88d76832ae7c
Revises: b1245503f2c9
Create Date: 2021-02-19 11:06:00.673208-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88d76832ae7c"
down_revision = "b1245503f2c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
