"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 8a35f3d1185f
Revises: 2353a01fd1ea
Create Date: 2021-02-19 09:04:34.408900-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a35f3d1185f"
down_revision = "2353a01fd1ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
