"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 8b913eacc183
Revises: 1ba2a91570f8
Create Date: 2021-03-02 08:21:38.793176-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b913eacc183"
down_revision = "1ba2a91570f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
