"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 90b5e040f9e1
Revises: bdadb55a8f60
Create Date: 2021-02-03 07:13:52.772617-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90b5e040f9e1"
down_revision = "bdadb55a8f60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
