"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 923cc8d5eb7e
Revises: 9dc849a1f19e
Create Date: 2021-02-18 06:26:13.503580-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "923cc8d5eb7e"
down_revision = "9dc849a1f19e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
