"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 954bf6feaa55
Revises: f115d551cd21
Create Date: 2020-09-18 07:14:37.487670-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "954bf6feaa55"
down_revision = "f115d551cd21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
