"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 9a859cae87f2
Revises: c84986c5e37a
Create Date: 2020-09-19 11:21:17.475623-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a859cae87f2"
down_revision = "c84986c5e37a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
