"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: 9dc849a1f19e
Revises: a2d7b88753a2
Create Date: 2021-02-17 03:59:52.895488-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dc849a1f19e"
down_revision = "a2d7b88753a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
