"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: a2d7b88753a2
Revises: 4e1ca92eb9a5
Create Date: 2021-02-16 08:56:24.799268-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2d7b88753a2"
down_revision = "4e1ca92eb9a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
