"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: b1245503f2c9
Revises: 8a35f3d1185f
Create Date: 2021-02-19 09:31:39.597978-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1245503f2c9"
down_revision = "8a35f3d1185f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
