"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: b5b65f4a6e2b
Revises: 2ddf4d8c19d6
Create Date: 2020-09-19 09:13:31.678982-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5b65f4a6e2b"
down_revision = "2ddf4d8c19d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
