"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: b6dab723d69d
Revises: 90b5e040f9e1
Create Date: 2021-02-03 07:23:13.782025-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6dab723d69d"
down_revision = "90b5e040f9e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
