"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: bdadb55a8f60
Revises: 24cc395286fb
Create Date: 2021-02-03 07:04:45.730586-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bdadb55a8f60"
down_revision = "24cc395286fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
