"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: c038aa65ba53
Revises: b6dab723d69d
Create Date: 2021-02-03 07:32:52.248083-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c038aa65ba53"
down_revision = "b6dab723d69d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
