"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: c544daef6c1e
Revises: 366df47dad2c
Create Date: 2021-02-03 06:05:22.152965-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c544daef6c1e"
down_revision = "366df47dad2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
