"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: c84986c5e37a
Revises: b5b65f4a6e2b
Create Date: 2020-09-19 09:38:51.867806-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c84986c5e37a"
down_revision = "b5b65f4a6e2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
