"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: ccbce38126ab
Revises: 472533d0a16a
Create Date: 2021-03-12 05:19:48.665330-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbce38126ab'
down_revision = '472533d0a16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
