"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: ced43aed2403
Revises: 0a35fa1dd78e
Create Date: 2021-03-08 08:04:03.328913-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ced43aed2403"
down_revision = "0a35fa1dd78e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
