"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: cf7195573e77
Revises: 91979b40eb38
Create Date: 2020-09-03 14:36:51.864216-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf7195573e77"
down_revision = "91979b40eb38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("can_sync", sa.Boolean(), nullable=True))
    op.add_column(
        "user", sa.Column("is_contributor", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "user", sa.Column("organization", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "user", sa.Column("username", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.drop_column("user", "first_name")
    op.drop_column("user", "address")
    op.drop_column("user", "last_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "last_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "address",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "first_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("user", "username")
    op.drop_column("user", "organization")
    op.drop_column("user", "name")
    op.drop_column("user", "is_contributor")
    op.drop_column("user", "can_sync")
    # ### end Alembic commands ###
