"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: d831f4f7b1ea
Revises: df2250026386
Create Date: 2021-03-02 05:13:49.657711-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d831f4f7b1ea"
down_revision = "df2250026386"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
