"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: dc0acc201ad8
Revises: 018bac35d473
Create Date: 2020-09-11 12:58:39.241099-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc0acc201ad8"
down_revision = "018bac35d473"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
