"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: df2250026386
Revises: 88d76832ae7c
Create Date: 2021-02-22 07:22:05.768938-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df2250026386"
down_revision = "88d76832ae7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
