"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: e2e97362c426
Revises: 6a21b8ea31fd
Create Date: 2021-03-11 06:18:02.147071-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2e97362c426"
down_revision = "6a21b8ea31fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
