"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: eaff12dbec3b
Revises: 954bf6feaa55
Create Date: 2020-09-18 08:49:33.440700-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eaff12dbec3b"
down_revision = "954bf6feaa55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
