"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: ef90ab83a49c
Revises: 78fbb708ad0c
Create Date: 2021-02-04 04:09:07.789017-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef90ab83a49c"
down_revision = "78fbb708ad0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
