"""Add columns username, name, organization, is_contributor and can_sync to User model.

Revision ID: f115d551cd21
Revises: c0e6cbf1f736
Create Date: 2020-09-14 14:35:52.777333-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f115d551cd21"
down_revision = "c0e6cbf1f736"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
